### ISSUE TITLE
Update docs to v 1.1 at docs.dataforsyningen.dk

### ISSUE THREAD

**Issue by kbevers** [SDFIdk/WEBPROJ#41]
From https://docs.dataforsyningen.dk/#webproj

![image](https://user-images.githubusercontent.com/13132571/173773219-b5648ede-b88f-4034-be45-802b6aa103be.png)

Should be version 1.1.0 now.

**Comment by larsnaesbye** [comment]
It might be worth a while to switch to [`apispec`](https://apispec.readthedocs.io/en/latest/index.html) instead, which can generate both version 2 (Swagger) and 3 (OpenAPI).

**Comment by kbevers** [comment]
> It might be worth a while to switch to [apispec](https://apispec.readthedocs.io/en/latest/index.html) instead, which can generate both version 2 (Swagger) and 3 (OpenAPI).

How does that integrate with flask_restx?

**Comment by larsnaesbye** [comment]
The only other options I see are
1) to continue to expose Swagger 2.0, but fix the inconsistencies and still manually convert and tweak at every release
2) to improve flask_restx

**Comment by larsnaesbye** [comment]
Last release and commit 10 months ago. I think it’s the sure way of getting voted in as maintainer….

**Comment by larsnaesbye** [comment]
To fix the current problem right here and now, I can generate the faulty Swagger 2.0 descriptor, alter the duplicates, convert it using Mermade and make a PR to docs.

**Comment by larsnaesbye** [comment]
Pulled. Now awaiting deployment into production.

**Comment by kbevers** [comment]
Cool. It would be nice to have the procedure described in a HOWTORELEASE file. Do you mind doing that?

**Comment by larsnaesbye** [comment]
I'll look into it.

Also, closing this because the new version has been deployed.
