### ISSUE TITLE
Add metadata to flask_restx.Api call

### ISSUE THREAD

**Issue by larsnaesbye** [SDFIdk/WEBPROJ#45]
Most of the metadata fields applicable to a Swagger definition can be set in the [flask_restx.Api](https://flask-restx.readthedocs.io/en/latest/api.html) call. This would facilitate removal of step 6i from the conversion to OpenAPI as mentioned under release instructions.

The information could for example be loaded from a JSON file.

**Comment by kbevers** [comment]
Which fields are relevant to fill out?

**Comment by kbevers** [comment]
Closed with #46
